`import DS from 'ember-data'`

User = DS.Model.extend
  login: DS.attr()
  avatar_url: DS.attr()
  gravatar_id: DS.attr()
  url: DS.attr()
  html_url: DS.attr()
  followers_url: DS.attr()
  following_url: DS.attr()
  gists_url: DS.attr()
  starred_url: DS.attr()
  subscriptions_url: DS.attr()
  organizations_url: DS.attr()
  repos_url: DS.attr()
  events_url: DS.attr()
  received_events_url: DS.attr()
  type: DS.attr()
  site_admin: DS.attr()
  name: DS.attr()
  company: DS.attr()
  blog: DS.attr()
  location: DS.attr()
  email: DS.attr()
  hireable: DS.attr()
  bio: DS.attr()
  public_repos: DS.attr()
  public_gists: DS.attr()
  followers: DS.attr()
  following: DS.attr()
  created_at: DS.attr()
  updated_at: DS.attr()

`export default User`
